#!/usr/bin/env python

import time

import automationhat
time.sleep(0.1) # short pause after ads1015 class creation recommended


print("""
Press CTRL+C to exit.
""")
itteration = 0
LightIntensity=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
while itteration < 24:
    value = automationhat.analog.two.read()
    print(value)
    LightIntensity[itteration]=value
    # print
    itteration = itteration + 1
    time.sleep(1)

import matplotlib.pyplot as plt 
plt.plot(LightIntensity) 
plt.ylabel('Light Intensity')
plt.show()
 
exit()
